### ISSUE TITLE
Learn about Laravel Model (ORM) share it with everyone

### ISSUE THREAD

**Issue by scala-next-mandalay** [scala-next-mandalay/rookie-training-2019-shop-backend#9]
Learn about ORM (Object-relational Mapping)
https://www.quora.com/What-is-Eloquent-ORM-in-Laravel
https://laravel.com/docs/5.8/eloquent

**Comment by kondows95** [comment]
@thandarlay 
Learn how to use Laravel's ORM with the highest priority.
This is the knowledge you need right now.
